trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: S3Upload@1
  inputs:
    awsCredentials: 'AWS-S3 Connection'
    regionName: 'us-east-1'
    bucketName: 'CurrentTimeServiceBucket'
    sourceFolder: 'CurrentTimeService'
    globExpressions: '**'
    createBucket: true
- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'AWS-S3 Connection'
    regionName: 'us-east-1'
    stackName: 'CurrentTimeServiceDemo'
    templateSource: 's3'
    s3BucketName: 'DevOpsDemo'      
